import React from "react";
import { graphql, PageProps, Link } from "gatsby";
import Layout from "../components/Layout";

interface ReviewData {
  mdx: {
    frontmatter: {
      title: string;
      date: string;
      source: string;
      arxivId?: string;
      similarityScore: number;
      excerpt: string;
      tags: string[];
      authors?: string[];
      paperUrl?: string;
    };
  };
}

const ReviewTemplate: React.FC<PageProps<ReviewData>> = ({ data, children }) => {
  const { frontmatter } = data.mdx;

  return (
    <Layout>
      <article className="py-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Back link */}
          <Link
            to="/"
            className="inline-flex items-center text-blue-600 hover:text-blue-800 mb-8 transition-colors"
          >
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Back to reviews
          </Link>

          {/* Header */}
          <header className="mb-8">
            <div className="flex flex-wrap items-center gap-3 text-sm text-gray-500 mb-4">
              <span>{frontmatter.date}</span>
              <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
              <span>{frontmatter.source}</span>
              {frontmatter.arxivId && (
                <>
                  <span className="w-1 h-1 bg-gray-300 rounded-full"></span>
                  <a
                    href={`https://arxiv.org/abs/${frontmatter.arxivId}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                  >
                    arXiv:{frontmatter.arxivId}
                  </a>
                </>
              )}
            </div>

            <h1 className="text-3xl lg:text-4xl font-bold text-gray-900 mb-4">
              {frontmatter.title}
            </h1>

            {frontmatter.authors && frontmatter.authors.length > 0 && (
              <p className="text-gray-600 mb-4">
                <strong>Authors:</strong> {frontmatter.authors.join(", ")}
              </p>
            )}

            <div className="flex flex-wrap gap-2 mb-6">
              <span
                className={`px-3 py-1 rounded-full text-sm font-medium ${
                  frontmatter.similarityScore >= 0.8
                    ? 'bg-green-100 text-green-800'
                    : 'bg-yellow-100 text-yellow-800'
                }`}
              >
                {Math.round(frontmatter.similarityScore * 100)}% relevance match
              </span>
              {frontmatter.tags.map(t => (
                <span key={t} className="px-3 py-1 rounded-full text-sm font-medium bg-gray-100 text-gray-700">
                  {t}
                </span>
              ))}
            </div>

            {frontmatter.paperUrl && (
              <a
                href={frontmatter.paperUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center bg-blue-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors"
              >
                Read Original Paper
                <svg className="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                </svg>
              </a>
            )}
          </header>

          {/* Content */}
          <div className="prose prose-lg max-w-none prose-headings:font-bold prose-headings:text-gray-900 prose-p:text-gray-700 prose-a:text-blue-600 prose-a:no-underline hover:prose-a:underline prose-code:bg-gray-100 prose-code:px-1 prose-code:rounded">
            {children}
          </div>

          {/* Footer */}
          <footer className="mt-12 pt-8 border-t border-gray-200">
            <div className="bg-blue-50 rounded-xl p-6">
              <h3 className="font-semibold text-gray-900 mb-2">About This Review</h3>
              <p className="text-gray-600 text-sm">
                This review was auto-generated by the Swarm-It research discovery pipeline.
                The analysis is certified using 3-agent RSCT (Representation-Solver Compatibility Testing)
                to ensure quality and relevance.
              </p>
            </div>
          </footer>
        </div>
      </article>
    </Layout>
  );
};

export const query = graphql`
  query ReviewPage($id: String!) {
    mdx(id: { eq: $id }) {
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        source
        arxivId
        similarityScore
        excerpt
        tags
        authors
        paperUrl
      }
    }
  }
`;

export default ReviewTemplate;
